### ISSUE TITLE
Class components compatibility

### ISSUE THREAD

**Issue by Ashilex** [madox2/react-tagcloud#39]
Is usage supported in react class components?
I am using react@16.14.0

error reported in console
```
react.development.js:1622  Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at useState (react.development.js:1622:1)
    at TagCloud (TagCloud.js:161:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
```

thanks

**Comment by madox2** [comment]
Hi, hooks has been introduced in react 16.8.0, so I suppose it should work. Anyway you could try to use version before hooks, although it might miss some features:

```
# react < 16.8.0
npm install react-tagcloud@1.4
```

**Comment by madox2** [comment]
Closing due to inactivity
